layout: sidebar # stacked or sidebar
style: light # dark or light

url: "https://alexmolas.github.io" # the base hostname & protocol for your site

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-seo-tag


paginate: 6

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  linkedin: alex-molas
  twitter: MolasAlex

about:
  - name: D
    position: C
    period: O

contact:
  - name: D
    position: C
    period: O

tags:
