layout: sidebar # stacked or sidebar
style: light # dark or light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: alex-molas
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Machine Learning 
    web_url: https://en.wikipedia.org/wiki/Machine_learning
    image_url: https://www.flaticon.com/svg/static/icons/svg/2103/2103718.svg
  
  - name: Operations Research
    web_url: https://en.wikipedia.org/wiki/Data_science
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Directed.svg/1920px-Directed.svg.png

education:
  - name: University of Virginia, School of Data Science • Charlottesville, Virginia
    position: M.S. Candidate in Data Science
    period: July 2020 - May 2021

  - name: Beijing Language and Culture University (北京语言大学) • Beijing, PRC
    position: Certificate in Intensive Mandarin
    period: September 2018 - December 2018

  - name: University of Michigan, College of Literature, Science, and the Arts • Ann Arbor, Michigan
    position: B.S. in Economics with High Honors •  Minor in Mathematics
    position2: Undergraduate Thesis - Playing by the Rules; How had the TRIPS Agreement Affected IP Adherence?
    period: September 2016 - May 2020
  
  - name: Delton Kellogg High School • Delton, Michigan
    position: High School Diploma
    period: September 2012 - May 2016


about:
  - name: D
    position: C
    period: O


works:
  - name: Data Visualization Specialist
    position: • Ann Arbor, Michigan
    position2: Clark Data Labs
    period: October 2019 - April 2020

contact:
  - name: D
    position: C
    period: O



theme: jekyll-theme-minimal