name: RSS Notifier

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute RSS Notifier
        run: python _tools/build_rss.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "alexmolasmartin@gmail.com"
          git config --local user.name "GitHub Action"
          git add _layouts/blogroll.html
          git diff --quiet && git diff --staged --quiet || git commit -m "update blogroll"
          git push
